# Generated by Django 4.0.3 on 2022-03-16 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='', verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='About me')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('gender', models.CharField(choices=[['male', 'Male'], ['female', 'Female']], default='male', max_length=10, verbose_name='Gender')),
                ('relationship', models.CharField(choices=[['none', 'None'], ['single', 'Single'], ['in_a_rel', 'In a relationship'], ['engaged', 'Engaged'], ['married', 'Married'], ['in_love', 'In love'], ['complicated', 'Complicated']], default='none', max_length=20, verbose_name='Relationship')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
